### ISSUE TITLE
Script non trovato

### ISSUE THREAD

**Issue by jenkin** [piggio/Memento#2]
[Questa linea](https://github.com/piggio/Memento/blob/bd88b6294af1dacea720edfa8297531b6adc8622/landing-page.html#L389) carica un js che non esiste nel repository. Forse manca il file di [questo plugin di jquery](http://guidobouman.github.io/jquery-panelsnap/)?

**Comment by vDarph** [comment]
Abbiamo risolto implementando correttamente scrollify.js
È sorto un problema nella landing page: facendo una prima scrollata, l'intera pagina scrolla dell'altezza del div dell'header, e la landing non rimane ancorata. Come possiamo risolvere ciò?

**Comment by jenkin** [comment]
Mi sa che devi ancora fare push delle modifiche, però...

**Comment by vDarph** [comment]
LE modifiche sono nella branch New-Landing. Il push lo vedo nella storia, quindi dovrebbe esserci.

**Comment by vDarph** [comment]
Come faccio per aggiornare il file con le sue modifiche? Non trovo il suo commit.

**Comment by jenkin** [comment]
Accetta [questa pull request](https://github.com/piggio/Memento/pull/3) e fai pull della master sul tuo pc.

**Comment by vDarph** [comment]
Grazie mille!
